name: "Deploy Now: Execute Build"

on:
  workflow_call:
    inputs:
      site-url:
        required: true
        type: string
      branch-id:
        required: true
        type: string

env:
  DEPLOYMENT_FOLDER: ./

jobs:
  # Build job
  build-project:
    name: build aibloggy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: "recursive"

  # Start server job
  start-server:
    name: Start Express Server
    runs-on: ubuntu-latest
    needs: build-project
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.17.1"  # Use the Node.js version you need

      - name: Install Dependencies
        run: npm install

      - name: Start Server
        run: node server.js &  # Start your Express server

  # Deploy job
  deploy:
    name: Deploy to Ionos
    runs-on: ubuntu-latest
    needs: start-server  # Wait for the server to start
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Deploy to Ionos
        uses: ionos-deploy-now/artifact-action@v1
        with:
          api-key: ${{ secrets.IONOS_API_KEY }}
          service-host: api-us.ionos.space
          project-id: 27ac9277-e217-4fce-8b1f-a12306a65834
          branch-id: ${{ inputs.branch-id }}
          version: ${{ github.sha }}
          folder: ${{ env.DEPLOYMENT_FOLDER }}
          config-file: .deploy-now/aibloggy/config.yaml
          action: upload